clear all
close all
clc

% Practical SMC-generated noise template. You need to change the file name
% with the latest collected measurement! Its name will be
% 'practical_smc_noise.csv'
smc_generated_noise = readmatrix('smc_example_new.csv');

% The moving mean is calculated for smoother visualization
smc_generated_noise = movmean(smc_generated_noise,5);

% The noise template generated by the VAE model
noise_template = readmatrix('noise_template.csv');

% Visualizing both SMC-generated noise (practical template) and VAE-created noise template (analytical template)

plot(smc_generated_noise)

hold on

plot(noise_template)

